Repository FastCampus-Final-Group2/finalproject_server, pull requests merged in 2024-09, with the labels that each got.

#70 Refactor: 배송처/센터 상세정보 조회 로직 분리
  src/main/java/com/team2/finalproject/domain/center/controller/CenterController.java
  src/main/java/com/team2/finalproject/domain/center/controller/SwaggerCenterController.java
  src/main/java/com/team2/finalproject/domain/deliverydestination/controller/DeliveryDestinationController.java
  src/main/java/com/team2/finalproject/domain/deliverydestination/controller/SwaggerDeliveryDestinationController.java
  src/main/resources/application-dev.yaml.example
  src/main/resources/application-prod.yaml.example
Labels: refactor

#74 Merge: dev -> main
  src/main/java/com/team2/finalproject/domain/center/controller/CenterController.java
  src/main/java/com/team2/finalproject/domain/center/controller/SwaggerCenterController.java
  src/main/java/com/team2/finalproject/domain/deliverydestination/controller/DeliveryDestinationController.java
  src/main/java/com/team2/finalproject/domain/deliverydestination/controller/SwaggerDeliveryDestinationController.java
  src/main/resources/application-dev.yaml.example
  src/main/resources/application-prod.yaml.example
Labels: merge

#77 refactor : 주문 상세 확인 response 변경 및 추가
  src/main/java/com/team2/finalproject/domain/transportorder/controller/SwaggerTransportOrderController.java
  src/main/java/com/team2/finalproject/domain/transportorder/controller/TransportOrderController.java
  src/main/java/com/team2/finalproject/domain/transportorder/model/dto/response/TransportOrderResponse.java
  src/main/java/com/team2/finalproject/domain/transportorder/service/TransportOrderService.java
Labels: refactor

#80 Refactor/diapatch cancel exception handling#78
  src/main/java/com/team2/finalproject/domain/dispatch/controller/DispatchController.java
  src/main/java/com/team2/finalproject/domain/dispatch/controller/SwaggerDispatchController.java
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/request/DispatchCancelRequest.java
  src/main/java/com/team2/finalproject/domain/dispatch/service/DispatchService.java
  src/main/java/com/team2/finalproject/domain/dispatchnumber/exception/DispatchNumberErrorCode.java
  src/main/java/com/team2/finalproject/domain/dispatchnumber/repository/DispatchNumberRepository.java
Labels: refactor

#85 Feat : 오류 경우의 수 추가
  src/main/java/com/team2/finalproject/domain/center/model/dto/request/CenterRequest.java
  src/main/java/com/team2/finalproject/domain/center/model/dto/request/UpdateCenterRequest.java
  src/main/java/com/team2/finalproject/domain/center/model/dto/response/CenterResponse.java
  src/main/java/com/team2/finalproject/domain/center/model/entity/Center.java
  src/main/java/com/team2/finalproject/domain/deliverydestination/model/dto/request/DeliveryDestinationRequest.java
  src/main/java/com/team2/finalproject/domain/deliverydestination/model/dto/request/UpdateDeliveryDestinationRequest.java
  src/main/java/com/team2/finalproject/domain/deliverydestination/model/dto/response/DeliveryDestinationResponse.java
  src/main/java/com/team2/finalproject/domain/deliverydestination/model/entity/DeliveryDestination.java
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/response/CourseResponse.java
  src/main/java/com/team2/finalproject/domain/dispatch/repository/DispatchRepository.java
  src/main/java/com/team2/finalproject/domain/dispatchdetail/model/dto/response/DispatchDetailResponse.java
  src/main/java/com/team2/finalproject/domain/dispatchdetail/service/DispatchDetailService.java
  src/main/java/com/team2/finalproject/domain/transportorder/model/dto/request/TransportOrderRequest.java
  src/main/java/com/team2/finalproject/domain/transportorder/service/TransportOrderService.java
  src/main/java/com/team2/finalproject/domain/vehicle/model/entity/Vehicle.java
  src/main/java/com/team2/finalproject/domain/vehicle/model/type/VehicleType.java
  src/main/java/com/team2/finalproject/domain/vehicle/model/type/temp
  src/main/java/com/team2/finalproject/domain/vehicledetail/controller/temp
  src/main/java/com/team2/finalproject/domain/vehicledetail/exception/VehicleDetailErrorCode.java
  src/main/java/com/team2/finalproject/domain/vehicledetail/exception/VehicleDetailException.java
  src/main/java/com/team2/finalproject/domain/vehicledetail/model/dto/temp
  src/main/java/com/team2/finalproject/domain/vehicledetail/model/entity/VehicleDetail.java
  src/main/java/com/team2/finalproject/domain/vehicledetail/model/type/VehicleType.java
  src/main/java/com/team2/finalproject/domain/vehicledetail/repository/VehicleDetailRepository.java
  src/main/java/com/team2/finalproject/domain/vehicledetail/service/temp
  src/main/java/com/team2/finalproject/global/service/OptimizationService.java
  src/main/java/com/team2/finalproject/global/util/request/OptimizationRequest.java
  src/main/java/com/team2/finalproject/global/util/response/OptimizationResponse.java
Labels: enhancement

#87 fix: 배송처 예외 처리 수정, 비고 예외 처리 수정
  src/main/java/com/team2/finalproject/domain/center/repository/CenterRepository.java
  src/main/java/com/team2/finalproject/domain/deliverydestination/repository/DeliveryDestinationRepository.java
  src/main/java/com/team2/finalproject/domain/dispatchdetail/service/DispatchDetailService.java
  src/main/java/com/team2/finalproject/domain/users/controller/SwaggerUsersController.java
  src/main/java/com/team2/finalproject/domain/users/model/dto/request/LoginRequest.java
  src/main/java/com/team2/finalproject/domain/users/model/dto/request/RegisterAdminRequest.java
  src/main/java/com/team2/finalproject/domain/users/model/dto/request/RegisterDriverRequest.java
  src/main/java/com/team2/finalproject/domain/users/model/dto/request/RegisterSuperAdminRequest.java
Labels: bug

#91 feat : entity 컬럼 추가
  src/main/java/com/team2/finalproject/domain/dispatch/model/entity/Dispatch.java
  src/main/java/com/team2/finalproject/domain/dispatch/service/DispatchService.java
  src/main/java/com/team2/finalproject/domain/sm/model/entity/Sm.java
  src/main/java/com/team2/finalproject/domain/sm/model/type/ContractType.java
  src/main/java/com/team2/finalproject/domain/sm/model/type/temp
Labels: enhancement

#95 refactor: 차량 관제 탭, 배차 조회 검색 시작 날짜 LocalDateTime으로 변경
  src/main/java/com/team2/finalproject/domain/dispatch/exception/DispatchErrorCode.java
  src/main/java/com/team2/finalproject/domain/dispatch/repository/DispatchRepository.java
  src/main/java/com/team2/finalproject/domain/dispatchnumber/controller/SwaggerDispatchNumberController.java
  src/main/java/com/team2/finalproject/domain/dispatchnumber/model/dto/request/DispatchNumberSearchRequest.java
  src/main/java/com/team2/finalproject/domain/dispatchnumber/service/DispatchNumberService.java
Labels: refactor

#97 refactor/dispatch-detail-response#93
  src/main/java/com/team2/finalproject/domain/dispatchdetail/model/dto/response/DispatchDetailResponse.java
Labels: refactor

#108 배포 v1.0.2
  src/main/java/com/team2/finalproject/domain/deliverydestination/controller/SwaggerDeliveryDestinationController.java
  src/main/java/com/team2/finalproject/domain/deliverydestination/repository/DeliveryDestinationRepository.java
  src/main/java/com/team2/finalproject/domain/deliverydestination/service/DeliveryDestinationService.java
  src/main/java/com/team2/finalproject/global/annotation/ApiErrorResponse.java
  src/main/java/com/team2/finalproject/global/annotation/ApiErrorResponses.java
  src/main/java/com/team2/finalproject/global/config/SwaggerConfig.java
  src/main/java/com/team2/finalproject/global/exception/response/ErrorResponse.java
  src/main/java/com/team2/finalproject/global/swagger/customizer/CustomOperationCustomizer.java
  src/main/java/com/team2/finalproject/global/swagger/customizer/ErrorResponseExampleCustomizer.java
Labels: enhancement

#107 Refactor/dispatch update#99
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/request/DispatchUpdateRequest.java
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/response/DispatchUpdateResponse.java
  src/main/java/com/team2/finalproject/domain/dispatch/service/DispatchService.java
Labels: refactor

#110 Feat/transport order to dispatch#94
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/response/CourseResponse.java
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/response/DispatchResponse.java
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/response/StartStopoverResponse.java
  src/main/java/com/team2/finalproject/domain/transportorder/service/TransportOrderService.java
  src/main/java/com/team2/finalproject/global/service/OptimizationService.java
Labels: enhancement

#111 배포 v1.0.3
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/request/DispatchUpdateRequest.java
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/response/CourseResponse.java
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/response/DispatchResponse.java
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/response/DispatchUpdateResponse.java
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/response/StartStopoverResponse.java
  src/main/java/com/team2/finalproject/domain/dispatch/service/DispatchService.java
  src/main/java/com/team2/finalproject/domain/transportorder/service/TransportOrderService.java
  src/main/java/com/team2/finalproject/global/service/OptimizationService.java
Labels: enhancement

#118 Merge: dev -> main
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/request/DispatchConfirmRequest.java
  src/main/java/com/team2/finalproject/domain/dispatch/model/entity/Dispatch.java
Labels: merge

#124 배차상태 변경 및 배송지연 이슈 내용 변경
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/request/DispatchConfirmRequest.java
  src/main/java/com/team2/finalproject/domain/dispatch/model/entity/Dispatch.java
  src/main/java/com/team2/finalproject/domain/dispatch/model/type/DispatchStatus.java
  src/main/java/com/team2/finalproject/domain/dispatch/service/DispatchService.java
  src/main/java/com/team2/finalproject/domain/dispatchdetail/model/entity/DispatchDetail.java
  src/main/java/com/team2/finalproject/domain/dispatchdetail/service/DispatchDetailService.java
  src/main/java/com/team2/finalproject/domain/dispatchnumber/model/dto/response/DispatchListResponse.java
  src/main/java/com/team2/finalproject/domain/dispatchnumber/service/DispatchNumberService.java
Labels: refactor

#126 fix : 로그인 응답 한국어 미지원 해결
  src/main/java/com/team2/finalproject/global/security/filter/LoginAuthenticationFilter.java
Labels: bug

#112 Feat: DispatchNumber 도메인 테스트 코드 작성, BaseIntegrationTest 작성
  build.gradle
  src/main/java/com/team2/finalproject/domain/dispatchnumber/exception/DispatchNumberErrorCode.java
  src/test/java/com/team2/finalproject/domain/dispatchnumber/controller/DispatchNumberControllerTest.java
  src/test/java/com/team2/finalproject/util/BaseIntegrationTest.java
  src/test/resources/application-test.yaml
  src/test/resources/init-h2gis.sql
  src/test/resources/schema.sql
Labels: test

#122 Fix/차량 관제 배차 상세 확인 respones, swagger
  src/main/java/com/team2/finalproject/domain/dispatch/repository/DispatchRepository.java
  src/main/java/com/team2/finalproject/domain/dispatchdetail/controller/SwaggerDispatchDetailController.java
  src/main/java/com/team2/finalproject/domain/dispatchdetail/model/dto/response/DispatchDetailResponse.java
  src/main/java/com/team2/finalproject/domain/dispatchdetail/service/DispatchDetailService.java
Labels: bug

#129 refactor : 가용주문 계산 로직 변경 및 detailAddress의 NotBlank옵션 해제
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/request/DispatchUpdateRequest.java
  src/main/java/com/team2/finalproject/domain/dispatch/service/DispatchService.java
Labels: refactor

#130 feat : 계약 수 response에 추가
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/response/CourseResponse.java
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/response/DispatchResponse.java
  src/main/java/com/team2/finalproject/global/service/KakaoApiService.java
  src/main/java/com/team2/finalproject/global/service/OptimizationService.java
Labels: enhancement

#147 Merge: dev -> main
  src/main/java/com/team2/finalproject/domain/center/model/entity/Center.java
Labels: merge

#157 feat : 오류 주문 표기 수정
  src/main/java/com/team2/finalproject/domain/transportorder/service/TransportOrderService.java
Labels: enhancement

#167 Merge: dev -> main
  src/main/java/com/team2/finalproject/domain/dispatch/model/dto/request/DispatchConfirmRequest.java
  src/main/java/com/team2/finalproject/domain/dispatchdetail/model/entity/DispatchDetail.java
Labels: merge
